/**
 * /terms — Terms of Use
 * Operator: Estates AI Tool
 * Last reviewed: 29 May 2026
 * Governing law: England and Wales
 */

const NAVY = '#1A2E4A'
const BLUE = '#2E75B6'

function Section({ title, children }) {
  return (
    <section style={{ marginBottom: '32px' }}>
      <h2 style={{ fontSize: '16px', fontWeight: 700, color: NAVY, borderBottom: '2px solid #E5E7EB', paddingBottom: '8px', marginBottom: '14px' }}>
        {title}
      </h2>
      {children}
    </section>
  )
}

const body = { fontSize: '14px', color: '#333', lineHeight: 1.8, margin: '0 0 10px' }
const li   = { fontSize: '14px', color: '#333', lineHeight: 1.7, marginBottom: '6px' }

export default function TermsPage() {
  return (
    <div style={{ minHeight: '100vh', background: '#F7F9FC', fontFamily: 'Arial, sans-serif' }}>

      {/* Header */}
      <header style={{ background: NAVY, padding: '12px 24px' }}>
        <div style={{ maxWidth: '800px', margin: '0 auto', display: 'flex', alignItems: 'center', gap: '10px' }}>
          <a href="/" style={{ display: 'flex', alignItems: 'center', gap: '10px', textDecoration: 'none' }}>
            <div style={{ width: '32px', height: '32px', background: BLUE, borderRadius: '4px', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#fff', fontWeight: 700, fontSize: '13px' }}>AI</div>
            <span style={{ color: '#fff', fontWeight: 600, fontSize: '16px' }}>Estates AI Tool</span>
          </a>
        </div>
      </header>

      {/* Body */}
      <main style={{ maxWidth: '800px', margin: '0 auto', padding: '40px 24px 80px' }}>

        <h1 style={{ fontSize: '26px', fontWeight: 700, color: NAVY, margin: '0 0 8px' }}>
          Terms of Use
        </h1>
        <p style={{ ...body, color: '#666', marginBottom: '32px' }}>
          Last reviewed: 29 May 2026 &nbsp;|&nbsp; Governing law: England and Wales
        </p>

        <Section title="1. About this tool">
          <p style={body}>
            Estates AI Tool is an internal planning tool that generates indicative feasibility reports at{' '}
            <strong>RIBA Stage 0–1</strong> accuracy. It is operated for the benefit of authorised personnel
            engaged in early-stage estates planning and capital investment appraisal.
          </p>
          <p style={body}>
            Access is restricted to authorised users only. By entering your access code and using this tool
            you agree to these terms.
          </p>
        </Section>

        <Section title="2. What this tool produces — and what it does not">
          <p style={body}>
            All cost figures generated by this tool carry an inherent accuracy of <strong>±15–25%</strong>{' '}
            as defined by RICS NRM1 for order-of-cost estimates at RIBA Stage 0–1. Programme durations are
            indicative only. Outputs <strong>do not constitute</strong>:
          </p>
          <ul style={{ paddingLeft: '20px', margin: '0 0 10px' }}>
            <li style={li}>a formal cost plan prepared by a Chartered Quantity Surveyor;</li>
            <li style={li}>professional architectural, engineering, or project management advice;</li>
            <li style={li}>a valuation, appraisal, or investment recommendation;</li>
            <li style={li}>legal, planning, or regulatory advice of any kind.</li>
          </ul>
          <p style={body}>
            Reports are intended to inform internal discussion and early-stage decision-making only.
            Before committing to any expenditure, procurement action, or design brief, outputs must be
            reviewed and verified by an appropriately qualified professional — typically a Chartered
            Quantity Surveyor for cost matters and a qualified architect or project manager for programme.
          </p>
        </Section>

        <Section title="3. Professional indemnity position">
          <p style={body}>
            This tool is an internal aide, not a regulated professional service. Its outputs are analogous
            to a benchmark spreadsheet or early-stage desk study — useful for framing a conversation,
            not for signing off a budget.
          </p>
          <p style={{ ...body, background: '#EEF4FA', border: `1px solid ${BLUE}`, borderRadius: '4px', padding: '12px 14px' }}>
            <strong>What this means in practice:</strong> If you are using this tool for your own
            organisation&apos;s internal planning, no additional PI insurance is required beyond your
            organisation&apos;s existing professional liability cover. If you intend to present a report
            to an external party (client, funder, board outside the organisation) as a professional output,
            you must ensure that either (a) the recipient clearly understands its indicative nature and the
            disclaimer is visible in the report, or (b) the report has been independently reviewed and
            signed off by a qualified professional who carries appropriate PI cover.
          </p>
        </Section>

        <Section title="4. Authorised use">
          <p style={body}>You agree to use this tool solely for internal pre-design planning purposes and to:</p>
          <ul style={{ paddingLeft: '20px', margin: '0 0 10px' }}>
            <li style={li}>keep your access code confidential and not share it with unauthorised persons;</li>
            <li style={li}>treat all outputs as indicative and subject to professional review;</li>
            <li style={li}>not enter personal data about individuals into the questionnaire fields
              (the tool is designed for project-level data — building type, size, location — not personal records);</li>
            <li style={li}>not use the tool to generate reports intended to deceive or mislead any party about
              project costs or feasibility.</li>
          </ul>
        </Section>

        <Section title="5. Limitation of liability">
          <p style={body}>
            To the fullest extent permitted by law, the operator of this tool excludes all liability for:
          </p>
          <ul style={{ paddingLeft: '20px', margin: '0 0 10px' }}>
            <li style={li}>any financial loss arising from reliance on cost estimates, programme durations,
              or other outputs;</li>
            <li style={li}>errors, omissions, or inaccuracies in the underlying benchmark data (BCIS/RICS);</li>
            <li style={li}>temporary unavailability due to maintenance, Vercel infrastructure outages,
              or AI provider downtime;</li>
            <li style={li}>loss of report data after the 90-day retention period has elapsed.</li>
          </ul>
          <p style={body}>
            Nothing in these terms excludes liability for death or personal injury caused by negligence,
            or for fraudulent misrepresentation.
          </p>
        </Section>

        <Section title="6. Intellectual property">
          <p style={body}>
            Reports generated by this tool belong to the organisation or individual who generated them.
            The underlying software, cost model, and AI prompts remain proprietary. You may not attempt
            to reverse-engineer the tool, resell access, or redistribute generated reports as a commercial
            product without prior written consent.
          </p>
        </Section>

        <Section title="7. Data and privacy">
          <p style={body}>
            The project data you enter is processed as described in our{' '}
            <a href="/privacy" style={{ color: BLUE }}>Privacy Notice</a>.
            By using this tool you confirm that the project information you provide does not include
            personal data about identifiable individuals beyond what is strictly necessary, and that
            you have authority to submit that information.
          </p>
        </Section>

        <Section title="8. Changes to these terms">
          <p style={body}>
            These terms may be updated at any time. The current version is always available at{' '}
            <code>/terms</code>. Continued use after a revision constitutes acceptance.
          </p>
        </Section>

        <Section title="9. Governing law">
          <p style={body}>
            These terms are governed by the laws of England and Wales. Any dispute shall be subject
            to the exclusive jurisdiction of the courts of England and Wales.
          </p>
        </Section>

      </main>

      <footer style={{ borderTop: '1px solid #E5E7EB', padding: '16px 24px', textAlign: 'center' }}>
        <p style={{ color: '#999', fontSize: '12px', margin: 0 }}>
          Estates AI Tool &nbsp;·&nbsp;
          <a href="/privacy" style={{ color: BLUE }}>Privacy Notice</a>
          &nbsp;·&nbsp;
          <a href="/access" style={{ color: BLUE }}>Return to tool</a>
          &nbsp;·&nbsp; Last reviewed 29 May 2026
        </p>
      </footer>

    </div>
  )
}
