import { describe, it, expect } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

// User-facing source must not carry the old brand, and must not present the
// product or its reports as AI-generated. Storage keys (estatesAI_…) and
// comments are allowed — see CLAUDE.md "Brand" / "Do not rename".
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..')
const walk = d => fs.readdirSync(path.join(ROOT, d)).flatMap(f => {
  const rel = path.join(d, f)
  return fs.statSync(path.join(ROOT, rel)).isDirectory() ? walk(rel) : [rel.replace(/\\/g, '/')]
})
const FILES = [...walk('app'), ...walk('lib/docx'), 'lib/reportBuilder.js', 'lib/reportShared.js', 'lib/reportContent.js', 'lib/brand.js']
  .filter(f => /\.(jsx?|tsx?|css)$/.test(f))
const stripComments = s => s
  .replace(/\{\/\*[\s\S]*?\*\/\}/g, '')
  .replace(/\/\*[\s\S]*?\*\//g, '')
  .replace(/(^|[^:'"`])\/\/.*$/gm, '$1')

const OLD_BRAND = /Estates AI|estates-ai-tool\.vercel\.app|Smarter (property )?decisions|Better insights/i
const AI_CLAIM = /AI[- ](narrative|generated|invented|written)|written by AI|generated by AI|the AI (never|writes)|>AI</i

describe('brand copy', () => {
  it('finds the files it scans', () => {
    expect(FILES.length).toBeGreaterThan(20)
  })
  for (const f of FILES) {
    it(`${f} has no old brand name or AI-generated claim`, () => {
      const src = stripComments(fs.readFileSync(path.join(ROOT, f), 'utf8'))
      expect(src.match(OLD_BRAND)?.[0], f).toBeUndefined()
      expect(src.match(AI_CLAIM)?.[0], f).toBeUndefined()
    })
  }
})
